// Minimal sidebars for demo
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'book-overview',
    {
      type: 'autogenerated',
      dirName: 'module-01',
    },
    {
      type: 'autogenerated',
      dirName: 'module-02',
    },
    {
      type: 'autogenerated',
      dirName: 'module-03',
    },
    {
      type: 'autogenerated',
      dirName: 'module-04',
    },
  ],
};

export default sidebars;
